### ISSUE TITLE
Отсутствует любое упоминание о лицензии

### ISSUE THREAD

**Issue by nurupo** [NeedForKillTheGame/nfk-discord-bot#2]
Без лицензии никто не имеет права изменять, рапостранять и даже использовать код, что конфликтует с 

>Have fun.

в README - никакого фана тут иметь нельзя.

Достаточно просто добавь файл LICENSE с тестом лицензии и копирайт строкой в корень репозитория.

**Comment by Ypsckud** [comment]
Добавил, надеюсь имелось ввиду это

**Comment by Ypsckud** [comment]
Закрываю?)

**Comment by nurupo** [comment]
Было бы лучше [полный текст лицензии включить](https://creativecommons.org/publicdomain/zero/1.0/legalcode.txt), чтобы GitHub опознал ее как CC0, как на этом скриншоте.

![CC0](https://user-images.githubusercontent.com/1855294/78845542-d6af5b00-79d6-11ea-9826-0105ed950580.png)

**Comment by Ypsckud** [comment]
вроде сделал, но пока лицензия не отображается. Что я делаю не так?)

**Comment by nurupo** [comment]
Хм, без понятия, у меня всегда срабатывало. Твой текст лицензии так же идентичен тому что у меня в [`test0`](https://github.com/nurupo/test0).

Может гитхабу надо какое-то время чтобы он лицензию определил, а может он ее не переопределяет. В любом случае, полный текст лицензии лучше чем ссылка на нее. Считаю что эту issue можно закрывать.

**Comment by Ypsckud** [comment]
Ок, спасибо!
